Elasticsearch exporter: event publishing (#2395)
* Elasticsearch exporter: event publishing

Implement per document retry behavior and a set of tests verifying that
the retry behavior is correctly configured and executed in conjunction
with the BulkIndexer.

The change introduces helpers for creating a fake Elasticsearch endpoint
that accepts bulk requests. This allows us to test the retry behavior
in case of multiple scenarios.

* add missing header

* rename documentAction to itemRequest

* typo

* rerun CI

* review + more retry disabled tests

* test

retrigger CI after unrelated test failure on windows:

```
--- FAIL: Test_statsdreceiver_EndToEnd (0.00s)
    --- FAIL: Test_statsdreceiver_EndToEnd/default_config_with_9s_interval (0.00s)
        receiver_test.go:136:
            	Error Trace:	receiver_test.go:136
            	Error:      	Received unexpected error:
            	            	listen udp 127.0.0.1:50633: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
            	Test:       	Test_statsdreceiver_EndToEnd/default_config_with_9s_interval
FAIL
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/statsdreceiver
```